name: paynes_kassa
description: Paynes for cashiers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.6.1
  get: ^4.6.5
  easy_sidemenu: ^0.4.1+1
  google_fonts: ^4.0.3
  path_provider: ^2.0.12
  telegram_client: ^0.3.107
  permission_handler: ^10.2.0
  device_info_plus: ^8.1.0
  extended_masked_text: ^2.3.1
  pinput: ^2.2.30
  mask_text_input_formatter: ^2.4.0
  money_formatter: ^0.0.4
  printing: ^5.10.1
  pdf: ^3.9.0
  pretty_qr_code: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

