import '../../../../common/res/payments/payments.dart';
import '../../../../common/routes/names.dart';
import '../../../../common/style/images.dart';

class PayState {
  List<Payment> payments = [
    Payment(
      0,
      ImagesBox.rekvizitLogo,
      "Оплата по реквизитам",
      "📑 Оплата по реквизитам",
      AppRoutes.verifyWithQr,
    ),
    Payment(
      1,
      ImagesBox.budgetLogo,
      "Гос.платежи и ГСБДД (ГАИ)",
      "🏛 Гос. платежи и ГСБДД (ГАИ)",
      AppRoutes.verifyWithQr,
    ),
    Payment(
      2,
      ImagesBox.comunalLogo,
      "Коммунальные платежи",
      "🏡 Коммунальные платежи",
      AppRoutes.verifyWithQr,
    ),
    Payment(
      3,
      ImagesBox.creditPercentLogo,
      "Погашение кредита",
      "🏦 Погашение кредита",
      AppRoutes.verifyWithQr,
    ),
    Payment(
      4,
      ImagesBox.taxLogo,
      "Налоги",
      "⚖ Налоги",
      AppRoutes.verifyWithQr,
    ),
    Payment(
      5,
      ImagesBox.insuranceLogo,
      "Страхование",
      "🛡 Страхование",
      AppRoutes.verifyWithQr,
    ),
    Payment(
      6,
      ImagesBox.educationLogo,
      "Образование",
      "🎓 Образование",
      AppRoutes.verifyWithQr,
    ),
  ];

  List<Pay> budgetPays = [
    Pay(
      id: 0,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 1,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 2,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 3,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 4,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 5,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 6,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 7,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 8,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 9,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 10,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 11,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
    Pay(
      id: 12,
      iconLink: ImagesBox.mib_auksion_yur,
      title: 'БПИ Аукцион для юридических лиц',
      link: 'E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ',
      route: 'E-Auksion_yur',
      commissionPercent: 1.5,
      commissionSum: 2000,
    ),
  ];
}
