import '../../../../../../common/res/payments/payments.dart';
import '../../../../../../common/style/images.dart';

class GosUslugiState {
  List<Pay> uslugi = [
    Pay(
      id: 0,
      iconLink: ImagesBox.mib_auksion_yur,
      title: "E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ",
      link: "E-AUKSION.UZ ДЛЯ ЮРИДИЧЕСКИХ ЛИЦ",
      route: 'e-auksion_yur',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 1,
      iconLink: ImagesBox.mib_auksion_jis,
      title: "E-AUKSION.UZ ДЛЯ ФИЗИЧЕСКИХ ЛИЦ",
      link: "E-AUKSION.UZ ДЛЯ ФИЗИЧЕСКИХ ЛИЦ",
      route: 'e-auksion_jis',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 3,
      iconLink: ImagesBox.gubdd,
      title: "ШТРАФЫ ГУБДД",
      link: "ШТРАФЫ ГУБДД",
      route: 'gubdd',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 4,
      iconLink: ImagesBox.notarius,
      title: "НОТАРИУС",
      link: "НОТАРИУС",
      route: 'notarious',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 5,
      iconLink: ImagesBox.e_sud,
      title: "СУДЕБНЫЕ ПОШЛИНЫ",
      link: "СУДЕБНЫЕ ПОШЛИНЫ",
      route: 'e_sud',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 6,
      iconLink: ImagesBox.bio_passport,
      title: "БИОПАСПОРТ",
      link: "БИОПАСПОРТ",
      route: 'bio_passport',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 7,
      iconLink: ImagesBox.id_card,
      title: "МВД ОВИР (ЗА ID КАРТЫ)",
      link: "МВД ОВИР (ЗА ID КАРТЫ)",
      route: 'id_card',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 8,
      iconLink: ImagesBox.zagran_pasport,
      title: "ЗАГРАНПАСПОРТ",
      link: "ЗАГРАНПАСПОРТ",
      route: 'zagran_pasport',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 9,
      iconLink: ImagesBox.mamuriy,
      title: "E-JARIMA",
      link: "E-JARIMA",
      route: 'mamuriy',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 10,
      iconLink: ImagesBox.zags,
      title: "ЗАГС",
      link: "ЗАГС",
      route: 'zags',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 11,
      iconLink: ImagesBox.zamena_pravo,
      title: "ЗАМЕНА ВОДИТЕЛЬСКОГО УДОСТОВЕРЕНИЯ",
      link: "ЗАМЕНА ВОДИТЕЛЬСКОГО УДОСТОВЕРЕНИЯ",
      route: 'zamena_pravo',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 12,
      iconLink: ImagesBox.my_gov,
      title: "АГЕНТСТВО ГОС. УСЛУГ",
      link: "АГЕНТСТВО ГОС. УСЛУГ",
      route: 'my_gov',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
    Pay(
      id: 13,
      iconLink: ImagesBox.mib,
      title: "МИБ ИСПОЛНИТЕЛЬНЫЙ ДОКУМЕНТ",
      link: "МИБ ИСПОЛНИТЕЛЬНЫЙ ДОКУМЕНТ",
      route: 'mib',
      commissionPercent: 1,
      commissionSum: 2000,
    ),
  ];
}
